In [2]:
import numpy as np

In [5]:
lista = [1,2,3,4,5,6]
array = np.array(lista)
print(array)
print(lista)
print(type(list))
print(type(array))

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]
<class 'type'>
<class 'numpy.ndarray'>


In [7]:
arr_zeros= np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
array[0]=9
print(array)

[9 2 3 4 5 6]


In [10]:
#AMtrizes#
matrizes_zeros = np.zeros((5,3))
print(matrizes_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#Notas de Alunos#
lista_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(lista_notas)
print('Maximo:', notas.max())
print('Minimo:', notas.min())
print('Desvio Padrão:', notas.std())
print('Média:' , notas.mean())
print('Posião do Menor:', notas.argmin())
print('Posião do Menor:', notas.argmax())

Maximo: 9.8
Minimo: 5.6
Desvio Padrão: 1.5628179676469045
Média: 7.76
Posião do Menor: 1
Posião do Menor: 0


Mascara Boleana

In [4]:
covid_positive = np.array(['yes', 'no', 'no', 'yes', 'yes', 'no'])
mask = (covid_positive == 'yes')
print(mask)
covid_positive[mask] = 'C19'
print(covid_positive)

[ True False False  True  True False]
['C19' 'no' 'no' 'C19' 'C19' 'no']


In [9]:
notas = np.array([9.8, 5.6, 7.8, 9.1, 6.5])
mask_notas = notas >= 7
print(mask_notas)

[ True False  True  True False]
